default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.8325957145940461
    has_acceleration_limits: true
    max_acceleration: 1.5057137756908099
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.7627825445142729
    has_acceleration_limits: true
    max_acceleration: 0.6006954100828078
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.8675022996339325
    has_acceleration_limits: true
    max_acceleration: 0.41569700334476734
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.443460952792061
    has_acceleration_limits: true
    max_acceleration: 2.4488633731507514
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.9722220547535925
    has_acceleration_limits: true
    max_acceleration: 2.5105424711126543
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.141592653589793
    has_acceleration_limits: true
    max_acceleration: 3.8766598064316247
    has_jerk: false
