- ros_topic_name: "/joint_states"
  gz_topic_name: "/model/kuka/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "gz_to_ros"

- ros_topic_name: "/kuka/command"
  gz_topic_name: "/model/kuka/joint_cmd"
  ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  gz_type_name: "gz.msgs.JointTrajectory"
  direction: "ros_to_gz"

- ros_topic_name: "/tf"
  gz_topic_name: "/model/kuka/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: "gz_to_ros"
