# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# The default config of moveit does not take into account the jerk limits, the RuckigTrajectorySmoothing adapter must be
# added to the planning pipeline to support jerk limits

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 17.567841
    has_jerk: true
    max_jerk: 892.0286289
  joint_a2:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 2.101232
    has_jerk: true
    max_jerk: 886.576821
  joint_a3:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 10.738869
    has_jerk: true
    max_jerk: 516.588450
  joint_a4:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 27.276282
    has_jerk: true
    max_jerk: 175.806183
  joint_a5:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 21.786787
    has_jerk: true
    max_jerk: 156.995898
  joint_a6:
    has_velocity_limits: true
    max_velocity: 5.235983
    has_acceleration_limits: true
    max_acceleration: 112.291689
    has_jerk: true
    max_jerk: 57.552859
