default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.8643062867009474
    has_acceleration_limits: true
    max_acceleration: 29.217653885814848
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.8643062867009474
    has_acceleration_limits: true
    max_acceleration: 9.95144382738442
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 8.508476363481101
    has_acceleration_limits: true
    max_acceleration: 19.950234311298882
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 10.471962421996588
    has_acceleration_limits: true
    max_acceleration: 30.071400319668427
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 9.23453476366542
    has_acceleration_limits: true
    max_acceleration: 35.239714201864835
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 13.962634015954636
    has_acceleration_limits: true
    max_acceleration: 76.6640181711857
    has_jerk: false
